

- name: install
  apt: name=munin-node state=present

- name: Configure munin-node
  template: >
    src={{ item.src }}
    dest={{ item.dest }}
    owner=root
    group=root
    mode=644
  with_items:
    - { src: munin.conf.j2, dest: /etc/munin/munin.conf }
    - { src: hosts.conf.j2, dest: "{{ munin_conf_d_directory }}/hosts.conf" }
  notify: restart munin-node
